### ISSUE TITLE
Assignmentのサイズ指定がおかしい

### ISSUE THREAD

**Issue by bokusunny** [Motonary/Orbit#180]
## 概要
secondusではsmall指定するとlargeサイズになってしまう、tertiusではそもそもlaegeサイズの星が作れない、など

**Comment by rechtburg** [comment]
これ画像作ってないよ？

**Comment by bokusunny** [comment]
画像を作る、とは？

**Comment by rechtburg** [comment]
smallに設定した時（実際に作ってみたと思うのですが）の画像スクショしてませんか、
という意味でした。

**Comment by bokusunny** [comment]
<img width="1440" alt="2019-01-01 22 09 40" src="https://user-images.githubusercontent.com/39128496/50573177-ef16ea00-0e11-11e9-9704-8ce2bdadacce.png">
<img width="1440" alt="2019-01-01 22 09 47" src="https://user-images.githubusercontent.com/39128496/50573181-ffc76000-0e11-11e9-81d2-cbb60d31188e.png">

secondusでsizeをlargeに設定して水星を作った時

**Comment by bokusunny** [comment]
<img width="1440" alt="2019-01-01 22 12 18" src="https://user-images.githubusercontent.com/39128496/50573200-4a48dc80-0e12-11e9-98ed-17d46e056ea4.png">
<img width="1440" alt="2019-01-01 22 12 21" src="https://user-images.githubusercontent.com/39128496/50573202-546adb00-0e12-11e9-8353-f42a74c244e3.png">


secondusでsizeをsmallに設定して地球を作った時

**Comment by rechtburg** [comment]
これ、期限迫ってるときは、基本的に設定したサイズのpx比1.2倍になる設定だから
そのことではない？

**Comment by bokusunny** [comment]
そういうことか。勘違いでした。
こんなにでかくなるんだね笑

**Comment by rechtburg** [comment]
1.2倍だと結構でかいね。笑
