### ISSUE TITLE
ProjectPageで恒星と惑星を同時に選択・破壊できてしまう

### ISSUE THREAD

**Issue by bokusunny** [Motonary/Orbit#181]
## 概要
<img width="1440" alt="2019-01-01 21 56 31" src="https://user-images.githubusercontent.com/39128496/50573068-1371c700-0e10-11e9-83d3-d49ddf086702.png">

## その他
工数が大きいのでとりあえずIssueにしておくが解決は必須ではない。今後取り組みたければ取り組む。

**Comment by bokusunny** [comment]
深刻なバグなのでクローズはしない

**Comment by rechtburg** [comment]
この
> 解決断念

ってどういうこと？

**Comment by bokusunny** [comment]
@rechtburg 
> 工数が大きいのでとりあえずIssueにしておくが解決は必須ではない。今後取り組みたければ取り
