### ISSUE TITLE
historypageで破壊ボタンを使えないように

### ISSUE THREAD

**Issue by bokusunny** [Motonary/Orbit#192]
## 概要
historypageで使えるfooterのボタンはrestoreだけに限定すべきだが、現状破壊ボタンも使えてしまう上に使うと当然バグが発生するので、恒星選択時のブラックホールのように、UI的に破壊できないことを明示しかつクリックしても何も起きないようにする

**Comment by bokusunny** [comment]
一個だけだとバランス悪くなっちゃう気がするので前者でいいと思います

**Comment by yukishirota** [comment]
そもそも使えないものを表示するのはUX的に頂けないと思うけどな

**Comment by bokusunny** [comment]
この場合、ユーザー目線だとrestoreボタンが一個だけ浮いててそれが何か認識できるか微妙だとも思う
使えないとしても破壊ボタンが横にあった方がまだ類推できるんじゃないかな

**Comment by yukishirota** [comment]
チュートリアルモーダル作る方がいいと思うな、それなら

**Comment by yukishirota** [comment]
もしくは、historypageからの削除はリストアする必要のないものに対して完全に削除できるようにするとか

**Comment by bokusunny** [comment]
モーダル作る余力があるならそれでお願いしたい！

**Comment by bokusunny** [comment]
もともと、ここはdone -> destroyの二段階の想定だったんだよね。DBにも使われてないけどdone_flagってあるし。現状、doneとdestroyが一体化？しちゃってる
つまり、
> もしくは、historypageからの削除はリストアする必要のないものに対して完全に削除できるようにするとか

これへの移行はスムーズにできるしそれが本来ベタだと思う。
ただ、個人的にはBuddixに一刻も早く移行したいのであんま乗り気しないかも、、笑

**Comment by yukishirota** [comment]
バグ修正なら、もうコンポーネント表示しないのが一番いいかなぁ

**Comment by bokusunny** [comment]
これまでの議論を踏まえてそこをどうするかの判断は一任してもいい？

**Comment by yukishirota** [comment]
はい
